### ISSUE TITLE
(Lang i A) vs. (List i A → 𝟚)

### ISSUE THREAD

**Issue by andreasabel** [ayberkt/agda-brzozowski#6]
https://github.com/ayberkt/agda-brzozowski/blob/772faa8cf431dd33786e9a2f1dd32df1296d2cd9/CoalgebraicAutomata.agda#L68

You are using both (Lang i A) and (List i A → 𝟚); these are isomorphic.  Is there a reason to have both?
Eg. `lang` and `DA.o` both compute languages generated by an automaton state, but one for (Lang i A) and the other for (List i A → 𝟚.)

**Comment by ayberkt** [comment]
No reason to have both; I just did not realize that `o` and `lang` are the same when I was implementing the paper's construction in Agda. I now replaced `o` with `lang` everywhere and made `o` work with `Lang i`.

https://github.com/ayberkt/agda-brzozowski/blob/3817018b1890e4014e63b883ad7608121f519f27/CoalgebraicAutomata.agda#L67-L69
